# Generated by Django 5.2.1 on 2025-05-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identification', models.BigIntegerField(unique=True)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('motivation', models.TextField()),
                ('name_guardian', models.CharField(blank=True, max_length=100, null=True)),
                ('identification_guardian', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('address_guardian', models.CharField(blank=True, max_length=100, null=True)),
                ('email_guardian', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number_guardian', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
