services:
  - type: web
    name: registerbootcamp-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn register.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: register.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
