services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    staticPublishPath: staticfiles
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
